site_name: CSAF Lint
site_description: Experimental CSAF envelope and body profile validator.

theme:
  name: 'material'
  palette:
    scheme: slate
    primary: black
    accent: indigo

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sthagen/fluffy-funicular
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/shagen/csaf-lint
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/shage

repo_name: sthagen/fluffy-funicular
repo_url: https://github.com/sthagen/fluffy-funicular
edit_uri: ""

nav:
  - Introduction: 'index.md'
  - Install: 'install.md'
  - Usage: 'usage.md'

markdown_extensions:
  - mkautodoc
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

extra_javascript:
