site_name: CSAF Lint
site_description: Experimental CSAF envelope and body profile validator.

theme:
  name: 'material'
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sthagen/fluffy-funicular
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/shagen/csaf-lint
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/shage

copyright: Copyright &copy; 2021 Stefan Hagen under the MIT license

repo_name: sthagen/fluffy-funicular
repo_url: https://github.com/sthagen/fluffy-funicular
edit_uri: ""

plugins:
  - search

nav:
  - Introduction: 'index.md'
  - Install: 'install.md'
  - Usage: 'usage.md'
  - Changes: 'changes.md'

markdown_extensions:
  - mkautodoc
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

extra_javascript:
