site_name: CSAF Lint
site_description: Experimental CSAF envelope and body profile validator.

theme:
  name: 'material'

repo_name: sthagen/fluffy-funicular
repo_url: https://github.com/sthagen/fluffy-funicular
edit_uri: ""

nav:
  - Introduction: 'index.md'
  - Usage: 'usage.md'

markdown_extensions:
  - mkautodoc
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

extra_javascript:
  - 'js/chat.js'
  - 'js/sidecar-1.5.0.js'